export const TYPES = {
    uiOpenModal: 'open modal',
    uiCloseModal: 'close modal',
    calendarSetSelectedEvent: 'set selected event',
    calendarStartAddNewEvent: 'start add new event',
    calendarAddNewEvent: 'add new event',
    calendarClearSelectedEvent: 'clear selected event',
    calendarUpdateEvent: 'update event',
    calendarStartUpdateEvent: 'start update event',
    calendarDeleteEvent: 'delete event',
    calendarStartLoadEvents: 'start load events',
    calendarLoadEvents: 'load events',
    calendarLogout: 'calendar logout',
    authAuthenticated: 'authenticated login',
    authAuthenticatedFinish: 'finish authenticated login',
    authStartLogin: 'start login',
    authLogin: 'login',
    authStartRegister: 'regiser',
    authStartRenewToken: 'renew token',
    authLogout: 'logout',
}